# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 11:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlentry',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
